services:
  - type: web
    name: maxy-chat-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000
      - key: ENABLE_CREDITS
        value: "True"
      - key: HOST
        value: 0.0.0.0
